### ISSUE TITLE
Conflict with Elementor

### ISSUE THREAD

**Issue by kostsi** [papakigr/SimpleResellers-WordPressPlugin#7]
Όταν ενεργοποιείς το plugin του Papaki, ο Elementor δεν φορτώνει, καθώς και το carousel εικόνων του Elementor "σπάει".

**Comment by voulaTroulaki** [comment]
Γεια σας, ευχαριστούμε πολύ για το feedback, θα σας ενημερώσουμε μόλις διερευνήσουμε το πρόβλημα.

**Comment by kostsi** [comment]
Καλησπέρα, ευχαριστώ για την άμεση απάντηση.  
Για περισσότερες πληροφορίες σχετικά  με το conflict σας παραθέτω τα παρακάτω:

Έκδοση php: 7.4.16 
Wordpress version: 5.7
Elementor version: 3.1.4
Elementor Pro: 3.2.1
Papaki Domain Registration: 3.2.1

To πρόβλημα πιθανόν εστιάζεται στην έκδοση jquery που χρησιμοποιεί το plugin.

**Comment by gkapsal** [comment]
Καλησπέρα και συγνώμη για την καθυστέρηση.

Το plugin έχει γίνει update, ελπίζω να λύνει το πρόβλημα σου.

Στη διάθεση σου!
